{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Google.Protobuf.Field exposing
    ( Cardinality(..), Kind(..), decodeCardinality, decodeKind, defaultCardinality, defaultKind, encodeCardinality, encodeKind
    , fieldNumbersCardinality, fieldNumbersKind, fromInternalCardinality, fromInternalKind, toInternalCardinality, toInternalKind
    )

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.1.0-beta.1
  - `protoc` 4.22.2
  - the following specification files: `google/protobuf/type.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Cardinality, Kind, decodeCardinality, decodeKind, defaultCardinality, defaultKind, encodeCardinality, encodeKind
@docs fieldNumbersCardinality, fieldNumbersKind, fromInternalCardinality, fromInternalKind, toInternalCardinality, toInternalKind

-}

import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Cardinality`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersCardinality : Cardinality -> Int
fieldNumbersCardinality n_ =
    case n_ of
        CARDINALITYUNKNOWN ->
            0

        CARDINALITYOPTIONAL ->
            1

        CARDINALITYREQUIRED ->
            2

        CARDINALITYREPEATED ->
            3

        CardinalityUnrecognized_ m_ ->
            m_


{-| Default for Cardinality. Should only be used for 'required' decoders as an initial value.
-}
defaultCardinality : Cardinality
defaultCardinality =
    CARDINALITYUNKNOWN


{-| Convert a `Cardinality` into its internal representation `Proto__Google__Protobuf__Field__Cardinality`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
toInternalCardinality : Cardinality -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__Cardinality
toInternalCardinality data_ =
    case data_ of
        CARDINALITYUNKNOWN ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYUNKNOWN

        CARDINALITYOPTIONAL ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYOPTIONAL

        CARDINALITYREQUIRED ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYREQUIRED

        CARDINALITYREPEATED ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYREPEATED

        CardinalityUnrecognized_ n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CardinalityUnrecognized_ n_


{-| Convert the internal type `Proto__Google__Protobuf__Field__Cardinality` into a `Cardinality`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
fromInternalCardinality : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__Cardinality -> Cardinality
fromInternalCardinality data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYUNKNOWN ->
            CARDINALITYUNKNOWN

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYOPTIONAL ->
            CARDINALITYOPTIONAL

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYREQUIRED ->
            CARDINALITYREQUIRED

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CARDINALITYREPEATED ->
            CARDINALITYREPEATED

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__CardinalityUnrecognized_ n_ ->
            CardinalityUnrecognized_ n_


{-| Declares how to encode a `Cardinality` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeCardinality : Cardinality -> Protobuf.Encode.Encoder
encodeCardinality =
    toInternalCardinality >> Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Field__Cardinality


{-| Declares how to decode a `Cardinality` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeCardinality : Protobuf.Decode.Decoder Cardinality
decodeCardinality =
    Protobuf.Decode.map
        fromInternalCardinality
        Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Field__Cardinality


{-| Whether a field is optional, required, or repeated.
-}
type Cardinality
    = CARDINALITYUNKNOWN
    | CARDINALITYOPTIONAL
    | CARDINALITYREQUIRED
    | CARDINALITYREPEATED
    | CardinalityUnrecognized_ Int


{-| The field numbers for the fields of `Kind`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersKind : Kind -> Int
fieldNumbersKind n_ =
    case n_ of
        TYPEUNKNOWN ->
            0

        TYPEDOUBLE ->
            1

        TYPEFLOAT ->
            2

        TYPEINT64 ->
            3

        TYPEUINT64 ->
            4

        TYPEINT32 ->
            5

        TYPEFIXED64 ->
            6

        TYPEFIXED32 ->
            7

        TYPEBOOL ->
            8

        TYPESTRING ->
            9

        TYPEGROUP ->
            10

        TYPEMESSAGE ->
            11

        TYPEBYTES ->
            12

        TYPEUINT32 ->
            13

        TYPEENUM ->
            14

        TYPESFIXED32 ->
            15

        TYPESFIXED64 ->
            16

        TYPESINT32 ->
            17

        TYPESINT64 ->
            18

        KindUnrecognized_ m_ ->
            m_


{-| Default for Kind. Should only be used for 'required' decoders as an initial value.
-}
defaultKind : Kind
defaultKind =
    TYPEUNKNOWN


{-| Convert a `Kind` into its internal representation `Proto__Google__Protobuf__Field__Kind`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
toInternalKind : Kind -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__Kind
toInternalKind data_ =
    case data_ of
        TYPEUNKNOWN ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUNKNOWN

        TYPEDOUBLE ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEDOUBLE

        TYPEFLOAT ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFLOAT

        TYPEINT64 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEINT64

        TYPEUINT64 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUINT64

        TYPEINT32 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEINT32

        TYPEFIXED64 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFIXED64

        TYPEFIXED32 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFIXED32

        TYPEBOOL ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEBOOL

        TYPESTRING ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESTRING

        TYPEGROUP ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEGROUP

        TYPEMESSAGE ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEMESSAGE

        TYPEBYTES ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEBYTES

        TYPEUINT32 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUINT32

        TYPEENUM ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEENUM

        TYPESFIXED32 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESFIXED32

        TYPESFIXED64 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESFIXED64

        TYPESINT32 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESINT32

        TYPESINT64 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESINT64

        KindUnrecognized_ n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__KindUnrecognized_ n_


{-| Convert the internal type `Proto__Google__Protobuf__Field__Kind` into a `Kind`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
fromInternalKind : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__Kind -> Kind
fromInternalKind data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUNKNOWN ->
            TYPEUNKNOWN

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEDOUBLE ->
            TYPEDOUBLE

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFLOAT ->
            TYPEFLOAT

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEINT64 ->
            TYPEINT64

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUINT64 ->
            TYPEUINT64

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEINT32 ->
            TYPEINT32

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFIXED64 ->
            TYPEFIXED64

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEFIXED32 ->
            TYPEFIXED32

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEBOOL ->
            TYPEBOOL

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESTRING ->
            TYPESTRING

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEGROUP ->
            TYPEGROUP

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEMESSAGE ->
            TYPEMESSAGE

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEBYTES ->
            TYPEBYTES

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEUINT32 ->
            TYPEUINT32

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPEENUM ->
            TYPEENUM

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESFIXED32 ->
            TYPESFIXED32

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESFIXED64 ->
            TYPESFIXED64

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESINT32 ->
            TYPESINT32

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__TYPESINT64 ->
            TYPESINT64

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field__KindUnrecognized_ n_ ->
            KindUnrecognized_ n_


{-| Declares how to encode a `Kind` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeKind : Kind -> Protobuf.Encode.Encoder
encodeKind =
    toInternalKind >> Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Field__Kind


{-| Declares how to decode a `Kind` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeKind : Protobuf.Decode.Decoder Kind
decodeKind =
    Protobuf.Decode.map fromInternalKind Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Field__Kind


{-| Basic field types.
-}
type Kind
    = TYPEUNKNOWN
    | TYPEDOUBLE
    | TYPEFLOAT
    | TYPEINT64
    | TYPEUINT64
    | TYPEINT32
    | TYPEFIXED64
    | TYPEFIXED32
    | TYPEBOOL
    | TYPESTRING
    | TYPEGROUP
    | TYPEMESSAGE
    | TYPEBYTES
    | TYPEUINT32
    | TYPEENUM
    | TYPESFIXED32
    | TYPESFIXED64
    | TYPESINT32
    | TYPESINT64
    | KindUnrecognized_ Int
