{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Google.Protobuf.FieldOptions.OptionRetention exposing
    ( OptionRetention(..), decodeOptionRetention, defaultOptionRetention, encodeOptionRetention, fieldNumbersOptionRetention
    , jsonDecodeOptionRetention, jsonEncodeOptionRetention
    )

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.0
  - `protoc` 4.22.2
  - the following specification files: `google/protobuf/descriptor.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs OptionRetention, decodeOptionRetention, defaultOptionRetention, encodeOptionRetention, fieldNumbersOptionRetention

@docs jsonDecodeOptionRetention, jsonEncodeOptionRetention

-}

import Json.Decode
import Json.Encode
import Protobuf.Decode
import Protobuf.Encode
import Protobuf.Utils.Int32


{-| Decode a `OptionRetention` from JSON. Uses the canonical encoding described here: <https://protobuf.dev/programming-guides/proto3/#json>
-}
jsonDecodeOptionRetention : Json.Decode.Decoder OptionRetention
jsonDecodeOptionRetention =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.map
                (\i ->
                    case i of
                        "RETENTION_UNKNOWN" ->
                            RETENTIONUNKNOWN

                        "RETENTION_RUNTIME" ->
                            RETENTIONRUNTIME

                        "RETENTION_SOURCE" ->
                            RETENTIONSOURCE

                        _ ->
                            RETENTIONUNKNOWN
                )
        , Protobuf.Utils.Int32.int32JsonDecoder
            |> Json.Decode.map
                (\i ->
                    case i of
                        0 ->
                            RETENTIONUNKNOWN

                        1 ->
                            RETENTIONRUNTIME

                        2 ->
                            RETENTIONSOURCE

                        _ ->
                            RETENTIONUNKNOWN
                )
        ]


{-| Encode a `OptionRetention` to JSON. Uses the canonical encoding described here: <https://protobuf.dev/programming-guides/proto3/#json>
-}
jsonEncodeOptionRetention : OptionRetention -> Json.Encode.Value
jsonEncodeOptionRetention value =
    Json.Encode.string <|
        case value of
            RETENTIONUNKNOWN ->
                "RETENTION_UNKNOWN"

            RETENTIONRUNTIME ->
                "RETENTION_RUNTIME"

            RETENTIONSOURCE ->
                "RETENTION_SOURCE"


{-| The field numbers for the fields of `OptionRetention`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersOptionRetention : OptionRetention -> Int
fieldNumbersOptionRetention n_ =
    case n_ of
        RETENTIONUNKNOWN ->
            0

        RETENTIONRUNTIME ->
            1

        RETENTIONSOURCE ->
            2


{-| Default for OptionRetention. Should only be used for 'required' decoders as an initial value.
-}
defaultOptionRetention : OptionRetention
defaultOptionRetention =
    RETENTIONUNKNOWN


{-| Declares how to encode a `OptionRetention` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeOptionRetention : OptionRetention -> Protobuf.Encode.Encoder
encodeOptionRetention value =
    Protobuf.Encode.int32 <|
        case value of
            RETENTIONUNKNOWN ->
                0

            RETENTIONRUNTIME ->
                1

            RETENTIONSOURCE ->
                2


{-| Declares how to decode a `OptionRetention` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeOptionRetention : Protobuf.Decode.Decoder OptionRetention
decodeOptionRetention =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        RETENTIONUNKNOWN

                    1 ->
                        RETENTIONRUNTIME

                    2 ->
                        RETENTIONSOURCE

                    _ ->
                        RETENTIONUNKNOWN
            )


{-| `OptionRetention` enumeration
-}
type OptionRetention
    = RETENTIONUNKNOWN
    | RETENTIONRUNTIME
    | RETENTIONSOURCE
