{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Google.Protobuf.GeneratedCodeInfo.Annotation exposing (Semantic(..), decodeSemantic, defaultSemantic, encodeSemantic, fieldNumbersSemantic, fromInternalSemantic, toInternalSemantic)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.1.0-beta.1
  - `protoc` 4.22.2
  - the following specification files: `google/protobuf/descriptor.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Semantic, decodeSemantic, defaultSemantic, encodeSemantic, fieldNumbersSemantic, fromInternalSemantic, toInternalSemantic

-}

import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Semantic`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersSemantic : Semantic -> Int
fieldNumbersSemantic n_ =
    case n_ of
        NONE ->
            0

        SET ->
            1

        ALIAS ->
            2


{-| Default for Semantic. Should only be used for 'required' decoders as an initial value.
-}
defaultSemantic : Semantic
defaultSemantic =
    NONE


{-| Convert a `Semantic` into its internal representation `Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
toInternalSemantic : Semantic -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic
toInternalSemantic data_ =
    case data_ of
        NONE ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__NONE

        SET ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__SET

        ALIAS ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__ALIAS


{-| Convert the internal type `Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic` into a `Semantic`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
fromInternalSemantic : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic -> Semantic
fromInternalSemantic data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__NONE ->
            NONE

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__SET ->
            SET

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo__Annotation__ALIAS ->
            ALIAS


{-| Declares how to encode a `Semantic` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeSemantic : Semantic -> Protobuf.Encode.Encoder
encodeSemantic =
    toInternalSemantic
        >> Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic


{-| Declares how to decode a `Semantic` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeSemantic : Protobuf.Decode.Decoder Semantic
decodeSemantic =
    Protobuf.Decode.map
        fromInternalSemantic
        Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__GeneratedCodeInfo__Annotation__Semantic


{-| Represents the identified object's effect on the element in the original
.proto file.
-}
type Semantic
    = NONE
    | SET
    | ALIAS
