{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Google.Protobuf exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.0.1
- `protoc` 3.19.4
- the following specification files: `google/protobuf/any.proto, google/protobuf/api.proto, google/protobuf/descriptor.proto, google/protobuf/duration.proto, google/protobuf/empty.proto, google/protobuf/field_mask.proto, google/protobuf/source_context.proto, google/protobuf/struct.proto, google/protobuf/timestamp.proto, google/protobuf/type.proto, google/protobuf/wrappers.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


-}

import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| Default for BytesValue. Should only be used for 'required' decoders as an initial value.


-}
defaultBytesValue : BytesValue
defaultBytesValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__BytesValue


{-| Declares how to decode a `BytesValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeBytesValue : Protobuf.Decode.Decoder BytesValue
decodeBytesValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__BytesValue


{-| Declares how to encode a `BytesValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeBytesValue : BytesValue -> Protobuf.Encode.Encoder
encodeBytesValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__BytesValue


{-| `BytesValue` message


-}
type alias BytesValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__BytesValue


{-| Default for StringValue. Should only be used for 'required' decoders as an initial value.


-}
defaultStringValue : StringValue
defaultStringValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__StringValue


{-| Declares how to decode a `StringValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeStringValue : Protobuf.Decode.Decoder StringValue
decodeStringValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__StringValue


{-| Declares how to encode a `StringValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeStringValue : StringValue -> Protobuf.Encode.Encoder
encodeStringValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__StringValue


{-| `StringValue` message


-}
type alias StringValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__StringValue


{-| Default for BoolValue. Should only be used for 'required' decoders as an initial value.


-}
defaultBoolValue : BoolValue
defaultBoolValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__BoolValue


{-| Declares how to decode a `BoolValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeBoolValue : Protobuf.Decode.Decoder BoolValue
decodeBoolValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__BoolValue


{-| Declares how to encode a `BoolValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeBoolValue : BoolValue -> Protobuf.Encode.Encoder
encodeBoolValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__BoolValue


{-| `BoolValue` message


-}
type alias BoolValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__BoolValue


{-| Default for UInt32Value. Should only be used for 'required' decoders as an initial value.


-}
defaultUInt32Value : UInt32Value
defaultUInt32Value =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__UInt32Value


{-| Declares how to decode a `UInt32Value` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeUInt32Value : Protobuf.Decode.Decoder UInt32Value
decodeUInt32Value =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__UInt32Value


{-| Declares how to encode a `UInt32Value` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeUInt32Value : UInt32Value -> Protobuf.Encode.Encoder
encodeUInt32Value =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__UInt32Value


{-| `UInt32Value` message


-}
type alias UInt32Value =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__UInt32Value


{-| Default for Int32Value. Should only be used for 'required' decoders as an initial value.


-}
defaultInt32Value : Int32Value
defaultInt32Value =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Int32Value


{-| Declares how to decode a `Int32Value` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeInt32Value : Protobuf.Decode.Decoder Int32Value
decodeInt32Value =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Int32Value


{-| Declares how to encode a `Int32Value` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeInt32Value : Int32Value -> Protobuf.Encode.Encoder
encodeInt32Value =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Int32Value


{-| `Int32Value` message


-}
type alias Int32Value =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Int32Value


{-| Default for UInt64Value. Should only be used for 'required' decoders as an initial value.


-}
defaultUInt64Value : UInt64Value
defaultUInt64Value =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__UInt64Value


{-| Declares how to decode a `UInt64Value` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeUInt64Value : Protobuf.Decode.Decoder UInt64Value
decodeUInt64Value =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__UInt64Value


{-| Declares how to encode a `UInt64Value` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeUInt64Value : UInt64Value -> Protobuf.Encode.Encoder
encodeUInt64Value =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__UInt64Value


{-| `UInt64Value` message


-}
type alias UInt64Value =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__UInt64Value


{-| Default for Int64Value. Should only be used for 'required' decoders as an initial value.


-}
defaultInt64Value : Int64Value
defaultInt64Value =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Int64Value


{-| Declares how to decode a `Int64Value` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeInt64Value : Protobuf.Decode.Decoder Int64Value
decodeInt64Value =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Int64Value


{-| Declares how to encode a `Int64Value` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeInt64Value : Int64Value -> Protobuf.Encode.Encoder
encodeInt64Value =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Int64Value


{-| `Int64Value` message


-}
type alias Int64Value =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Int64Value


{-| Default for FloatValue. Should only be used for 'required' decoders as an initial value.


-}
defaultFloatValue : FloatValue
defaultFloatValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FloatValue


{-| Declares how to decode a `FloatValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFloatValue : Protobuf.Decode.Decoder FloatValue
decodeFloatValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FloatValue


{-| Declares how to encode a `FloatValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFloatValue : FloatValue -> Protobuf.Encode.Encoder
encodeFloatValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FloatValue


{-| `FloatValue` message


-}
type alias FloatValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FloatValue


{-| Default for DoubleValue. Should only be used for 'required' decoders as an initial value.


-}
defaultDoubleValue : DoubleValue
defaultDoubleValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__DoubleValue


{-| Declares how to decode a `DoubleValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeDoubleValue : Protobuf.Decode.Decoder DoubleValue
decodeDoubleValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__DoubleValue


{-| Declares how to encode a `DoubleValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeDoubleValue : DoubleValue -> Protobuf.Encode.Encoder
encodeDoubleValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__DoubleValue


{-| `DoubleValue` message


-}
type alias DoubleValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DoubleValue


{-| Default for Timestamp. Should only be used for 'required' decoders as an initial value.


-}
defaultTimestamp : Timestamp
defaultTimestamp =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Timestamp


{-| Declares how to decode a `Timestamp` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTimestamp : Protobuf.Decode.Decoder Timestamp
decodeTimestamp =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Timestamp


{-| Declares how to encode a `Timestamp` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTimestamp : Timestamp -> Protobuf.Encode.Encoder
encodeTimestamp =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Timestamp


{-| `Timestamp` message


-}
type alias Timestamp =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Timestamp


{-| Default for ListValue. Should only be used for 'required' decoders as an initial value.


-}
defaultListValue : ListValue
defaultListValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ListValue


{-| Declares how to decode a `ListValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeListValue : Protobuf.Decode.Decoder ListValue
decodeListValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ListValue


{-| Declares how to encode a `ListValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeListValue : ListValue -> Protobuf.Encode.Encoder
encodeListValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ListValue


{-| `ListValue` message


-}
type alias ListValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ListValue


{-| Default for Value. Should only be used for 'required' decoders as an initial value.


-}
defaultValue : Value
defaultValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Value


{-| Declares how to decode a `Value` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeValue : Protobuf.Decode.Decoder Value
decodeValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Value


{-| Declares how to encode a `Value` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeValue : Value -> Protobuf.Encode.Encoder
encodeValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Value


{-| `Value` message


-}
type alias Value =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value


{-| Default for Struct. Should only be used for 'required' decoders as an initial value.


-}
defaultStruct : Struct
defaultStruct =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Struct


{-| Declares how to decode a `Struct` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeStruct : Protobuf.Decode.Decoder Struct
decodeStruct =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Struct


{-| Declares how to encode a `Struct` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeStruct : Struct -> Protobuf.Encode.Encoder
encodeStruct =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Struct


{-| `Struct` message


-}
type alias Struct =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Struct


{-| Default for FieldMask. Should only be used for 'required' decoders as an initial value.


-}
defaultFieldMask : FieldMask
defaultFieldMask =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FieldMask


{-| Declares how to decode a `FieldMask` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFieldMask : Protobuf.Decode.Decoder FieldMask
decodeFieldMask =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FieldMask


{-| Declares how to encode a `FieldMask` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFieldMask : FieldMask -> Protobuf.Encode.Encoder
encodeFieldMask =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FieldMask


{-| `FieldMask` message


-}
type alias FieldMask =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FieldMask


{-| Default for Empty. Should only be used for 'required' decoders as an initial value.


-}
defaultEmpty : Empty
defaultEmpty =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Empty


{-| Declares how to decode a `Empty` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEmpty : Protobuf.Decode.Decoder Empty
decodeEmpty =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Empty


{-| Declares how to encode a `Empty` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEmpty : Empty -> Protobuf.Encode.Encoder
encodeEmpty =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Empty


{-| `Empty` message


-}
type alias Empty =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Empty


{-| Default for Duration. Should only be used for 'required' decoders as an initial value.


-}
defaultDuration : Duration
defaultDuration =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Duration


{-| Declares how to decode a `Duration` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeDuration : Protobuf.Decode.Decoder Duration
decodeDuration =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Duration


{-| Declares how to encode a `Duration` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeDuration : Duration -> Protobuf.Encode.Encoder
encodeDuration =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Duration


{-| `Duration` message


-}
type alias Duration =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Duration


{-| Default for GeneratedCodeInfo. Should only be used for 'required' decoders as an initial value.


-}
defaultGeneratedCodeInfo : GeneratedCodeInfo
defaultGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__GeneratedCodeInfo


{-| Declares how to decode a `GeneratedCodeInfo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeGeneratedCodeInfo : Protobuf.Decode.Decoder GeneratedCodeInfo
decodeGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__GeneratedCodeInfo


{-| Declares how to encode a `GeneratedCodeInfo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeGeneratedCodeInfo : GeneratedCodeInfo -> Protobuf.Encode.Encoder
encodeGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__GeneratedCodeInfo


{-| `GeneratedCodeInfo` message


-}
type alias GeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo


{-| Default for SourceCodeInfo. Should only be used for 'required' decoders as an initial value.


-}
defaultSourceCodeInfo : SourceCodeInfo
defaultSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__SourceCodeInfo


{-| Declares how to decode a `SourceCodeInfo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeSourceCodeInfo : Protobuf.Decode.Decoder SourceCodeInfo
decodeSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__SourceCodeInfo


{-| Declares how to encode a `SourceCodeInfo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeSourceCodeInfo : SourceCodeInfo -> Protobuf.Encode.Encoder
encodeSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__SourceCodeInfo


{-| `SourceCodeInfo` message


-}
type alias SourceCodeInfo =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SourceCodeInfo


{-| Default for UninterpretedOption. Should only be used for 'required' decoders as an initial value.


-}
defaultUninterpretedOption : UninterpretedOption
defaultUninterpretedOption =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__UninterpretedOption


{-| Declares how to decode a `UninterpretedOption` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeUninterpretedOption : Protobuf.Decode.Decoder UninterpretedOption
decodeUninterpretedOption =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__UninterpretedOption


{-| Declares how to encode a `UninterpretedOption` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeUninterpretedOption : UninterpretedOption -> Protobuf.Encode.Encoder
encodeUninterpretedOption =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__UninterpretedOption


{-| `UninterpretedOption` message


-}
type alias UninterpretedOption =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__UninterpretedOption


{-| Default for MethodOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultMethodOptions : MethodOptions
defaultMethodOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MethodOptions


{-| Declares how to decode a `MethodOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMethodOptions : Protobuf.Decode.Decoder MethodOptions
decodeMethodOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MethodOptions


{-| Declares how to encode a `MethodOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMethodOptions : MethodOptions -> Protobuf.Encode.Encoder
encodeMethodOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MethodOptions


{-| `MethodOptions` message


-}
type alias MethodOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MethodOptions


{-| Default for ServiceOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultServiceOptions : ServiceOptions
defaultServiceOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ServiceOptions


{-| Declares how to decode a `ServiceOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeServiceOptions : Protobuf.Decode.Decoder ServiceOptions
decodeServiceOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ServiceOptions


{-| Declares how to encode a `ServiceOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeServiceOptions : ServiceOptions -> Protobuf.Encode.Encoder
encodeServiceOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ServiceOptions


{-| `ServiceOptions` message


-}
type alias ServiceOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ServiceOptions


{-| Default for EnumValueOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumValueOptions : EnumValueOptions
defaultEnumValueOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumValueOptions


{-| Declares how to decode a `EnumValueOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumValueOptions : Protobuf.Decode.Decoder EnumValueOptions
decodeEnumValueOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumValueOptions


{-| Declares how to encode a `EnumValueOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumValueOptions : EnumValueOptions -> Protobuf.Encode.Encoder
encodeEnumValueOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumValueOptions


{-| `EnumValueOptions` message


-}
type alias EnumValueOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumValueOptions


{-| Default for EnumOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumOptions : EnumOptions
defaultEnumOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumOptions


{-| Declares how to decode a `EnumOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumOptions : Protobuf.Decode.Decoder EnumOptions
decodeEnumOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumOptions


{-| Declares how to encode a `EnumOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumOptions : EnumOptions -> Protobuf.Encode.Encoder
encodeEnumOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumOptions


{-| `EnumOptions` message


-}
type alias EnumOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumOptions


{-| Default for OneofOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultOneofOptions : OneofOptions
defaultOneofOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__OneofOptions


{-| Declares how to decode a `OneofOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeOneofOptions : Protobuf.Decode.Decoder OneofOptions
decodeOneofOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__OneofOptions


{-| Declares how to encode a `OneofOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeOneofOptions : OneofOptions -> Protobuf.Encode.Encoder
encodeOneofOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__OneofOptions


{-| `OneofOptions` message


-}
type alias OneofOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__OneofOptions


{-| Default for FieldOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultFieldOptions : FieldOptions
defaultFieldOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FieldOptions


{-| Declares how to decode a `FieldOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFieldOptions : Protobuf.Decode.Decoder FieldOptions
decodeFieldOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FieldOptions


{-| Declares how to encode a `FieldOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFieldOptions : FieldOptions -> Protobuf.Encode.Encoder
encodeFieldOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FieldOptions


{-| `FieldOptions` message


-}
type alias FieldOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FieldOptions


{-| Default for MessageOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultMessageOptions : MessageOptions
defaultMessageOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MessageOptions


{-| Declares how to decode a `MessageOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMessageOptions : Protobuf.Decode.Decoder MessageOptions
decodeMessageOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MessageOptions


{-| Declares how to encode a `MessageOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMessageOptions : MessageOptions -> Protobuf.Encode.Encoder
encodeMessageOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MessageOptions


{-| `MessageOptions` message


-}
type alias MessageOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MessageOptions


{-| Default for FileOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultFileOptions : FileOptions
defaultFileOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileOptions


{-| Declares how to decode a `FileOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileOptions : Protobuf.Decode.Decoder FileOptions
decodeFileOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileOptions


{-| Declares how to encode a `FileOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileOptions : FileOptions -> Protobuf.Encode.Encoder
encodeFileOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileOptions


{-| `FileOptions` message


-}
type alias FileOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileOptions


{-| Default for MethodDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultMethodDescriptorProto : MethodDescriptorProto
defaultMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MethodDescriptorProto


{-| Declares how to decode a `MethodDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMethodDescriptorProto : Protobuf.Decode.Decoder MethodDescriptorProto
decodeMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MethodDescriptorProto


{-| Declares how to encode a `MethodDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMethodDescriptorProto : MethodDescriptorProto -> Protobuf.Encode.Encoder
encodeMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MethodDescriptorProto


{-| `MethodDescriptorProto` message


-}
type alias MethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MethodDescriptorProto


{-| Default for ServiceDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultServiceDescriptorProto : ServiceDescriptorProto
defaultServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ServiceDescriptorProto


{-| Declares how to decode a `ServiceDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeServiceDescriptorProto : Protobuf.Decode.Decoder ServiceDescriptorProto
decodeServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ServiceDescriptorProto


{-| Declares how to encode a `ServiceDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeServiceDescriptorProto : ServiceDescriptorProto -> Protobuf.Encode.Encoder
encodeServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ServiceDescriptorProto


{-| `ServiceDescriptorProto` message


-}
type alias ServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ServiceDescriptorProto


{-| Default for EnumValueDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumValueDescriptorProto : EnumValueDescriptorProto
defaultEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumValueDescriptorProto


{-| Declares how to decode a `EnumValueDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumValueDescriptorProto : Protobuf.Decode.Decoder EnumValueDescriptorProto
decodeEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumValueDescriptorProto


{-| Declares how to encode a `EnumValueDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumValueDescriptorProto : EnumValueDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumValueDescriptorProto


{-| `EnumValueDescriptorProto` message


-}
type alias EnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumValueDescriptorProto


{-| Default for EnumDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumDescriptorProto : EnumDescriptorProto
defaultEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumDescriptorProto


{-| Declares how to decode a `EnumDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumDescriptorProto : Protobuf.Decode.Decoder EnumDescriptorProto
decodeEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumDescriptorProto


{-| Declares how to encode a `EnumDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumDescriptorProto : EnumDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumDescriptorProto


{-| `EnumDescriptorProto` message


-}
type alias EnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumDescriptorProto


{-| Default for OneofDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultOneofDescriptorProto : OneofDescriptorProto
defaultOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__OneofDescriptorProto


{-| Declares how to decode a `OneofDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeOneofDescriptorProto : Protobuf.Decode.Decoder OneofDescriptorProto
decodeOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__OneofDescriptorProto


{-| Declares how to encode a `OneofDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeOneofDescriptorProto : OneofDescriptorProto -> Protobuf.Encode.Encoder
encodeOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__OneofDescriptorProto


{-| `OneofDescriptorProto` message


-}
type alias OneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__OneofDescriptorProto


{-| Default for FieldDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultFieldDescriptorProto : FieldDescriptorProto
defaultFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FieldDescriptorProto


{-| Declares how to decode a `FieldDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFieldDescriptorProto : Protobuf.Decode.Decoder FieldDescriptorProto
decodeFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FieldDescriptorProto


{-| Declares how to encode a `FieldDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFieldDescriptorProto : FieldDescriptorProto -> Protobuf.Encode.Encoder
encodeFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FieldDescriptorProto


{-| `FieldDescriptorProto` message


-}
type alias FieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FieldDescriptorProto


{-| Default for ExtensionRangeOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultExtensionRangeOptions : ExtensionRangeOptions
defaultExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ExtensionRangeOptions


{-| Declares how to decode a `ExtensionRangeOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeExtensionRangeOptions : Protobuf.Decode.Decoder ExtensionRangeOptions
decodeExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ExtensionRangeOptions


{-| Declares how to encode a `ExtensionRangeOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeExtensionRangeOptions : ExtensionRangeOptions -> Protobuf.Encode.Encoder
encodeExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ExtensionRangeOptions


{-| `ExtensionRangeOptions` message


-}
type alias ExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ExtensionRangeOptions


{-| Unwrap a `DescriptorProto` from its wrapper `DescriptorProto_.`


-}
unwrapDescriptorProto : DescriptorProto_ -> DescriptorProto
unwrapDescriptorProto =
    Proto.Google.Protobuf.Internals_.unwrapProto__Google__Protobuf__DescriptorProto


{-| Wrap a `DescriptorProto` into its wrapper `DescriptorProto_.`


-}
wrapDescriptorProto : DescriptorProto -> DescriptorProto_
wrapDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto_


{-| Type wrapper for alias type `DescriptorProto` to avoid unlimited recursion.


For a more in-depth explanation why we need this, read this: https://github.com/elm/compiler/blob/master/hints/recursive-alias.md.


-}
type alias DescriptorProto_ =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto_


{-| Default for DescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultDescriptorProto : DescriptorProto
defaultDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__DescriptorProto


{-| Declares how to decode a `DescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeDescriptorProto : Protobuf.Decode.Decoder DescriptorProto
decodeDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__DescriptorProto


{-| Declares how to encode a `DescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeDescriptorProto : DescriptorProto -> Protobuf.Encode.Encoder
encodeDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__DescriptorProto


{-| `DescriptorProto` message


-}
type alias DescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto


{-| Default for FileDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultFileDescriptorProto : FileDescriptorProto
defaultFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileDescriptorProto


{-| Declares how to decode a `FileDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileDescriptorProto : Protobuf.Decode.Decoder FileDescriptorProto
decodeFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileDescriptorProto


{-| Declares how to encode a `FileDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileDescriptorProto : FileDescriptorProto -> Protobuf.Encode.Encoder
encodeFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileDescriptorProto


{-| `FileDescriptorProto` message


-}
type alias FileDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileDescriptorProto


{-| Default for FileDescriptorSet. Should only be used for 'required' decoders as an initial value.


-}
defaultFileDescriptorSet : FileDescriptorSet
defaultFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileDescriptorSet


{-| Declares how to decode a `FileDescriptorSet` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileDescriptorSet : Protobuf.Decode.Decoder FileDescriptorSet
decodeFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileDescriptorSet


{-| Declares how to encode a `FileDescriptorSet` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileDescriptorSet : FileDescriptorSet -> Protobuf.Encode.Encoder
encodeFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileDescriptorSet


{-| `FileDescriptorSet` message


-}
type alias FileDescriptorSet =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileDescriptorSet


{-| Default for Mixin. Should only be used for 'required' decoders as an initial value.


-}
defaultMixin : Mixin
defaultMixin =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Mixin


{-| Declares how to decode a `Mixin` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMixin : Protobuf.Decode.Decoder Mixin
decodeMixin =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Mixin


{-| Declares how to encode a `Mixin` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMixin : Mixin -> Protobuf.Encode.Encoder
encodeMixin =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Mixin


{-| `Mixin` message


-}
type alias Mixin =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Mixin


{-| Default for Method. Should only be used for 'required' decoders as an initial value.


-}
defaultMethod : Method
defaultMethod =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Method


{-| Declares how to decode a `Method` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMethod : Protobuf.Decode.Decoder Method
decodeMethod =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Method


{-| Declares how to encode a `Method` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMethod : Method -> Protobuf.Encode.Encoder
encodeMethod =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Method


{-| `Method` message


-}
type alias Method =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Method


{-| Default for Api. Should only be used for 'required' decoders as an initial value.


-}
defaultApi : Api
defaultApi =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Api


{-| Declares how to decode a `Api` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeApi : Protobuf.Decode.Decoder Api
decodeApi =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Api


{-| Declares how to encode a `Api` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeApi : Api -> Protobuf.Encode.Encoder
encodeApi =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Api


{-| `Api` message


-}
type alias Api =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Api


{-| Default for Option. Should only be used for 'required' decoders as an initial value.


-}
defaultOption : Option
defaultOption =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Option


{-| Declares how to decode a `Option` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeOption : Protobuf.Decode.Decoder Option
decodeOption =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Option


{-| Declares how to encode a `Option` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeOption : Option -> Protobuf.Encode.Encoder
encodeOption =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Option


{-| `Option` message


-}
type alias Option =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Option


{-| Default for EnumValue. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumValue : EnumValue
defaultEnumValue =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumValue


{-| Declares how to decode a `EnumValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumValue : Protobuf.Decode.Decoder EnumValue
decodeEnumValue =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumValue


{-| Declares how to encode a `EnumValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumValue : EnumValue -> Protobuf.Encode.Encoder
encodeEnumValue =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumValue


{-| `EnumValue` message


-}
type alias EnumValue =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumValue


{-| Default for Enum. Should only be used for 'required' decoders as an initial value.


-}
defaultEnum : Enum
defaultEnum =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Enum


{-| Declares how to decode a `Enum` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnum : Protobuf.Decode.Decoder Enum
decodeEnum =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Enum


{-| Declares how to encode a `Enum` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnum : Enum -> Protobuf.Encode.Encoder
encodeEnum =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Enum


{-| `Enum` message


-}
type alias Enum =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Enum


{-| Default for Field. Should only be used for 'required' decoders as an initial value.


-}
defaultField : Field
defaultField =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Field


{-| Declares how to decode a `Field` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeField : Protobuf.Decode.Decoder Field
decodeField =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Field


{-| Declares how to encode a `Field` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeField : Field -> Protobuf.Encode.Encoder
encodeField =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Field


{-| `Field` message


-}
type alias Field =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Field


{-| Default for Type. Should only be used for 'required' decoders as an initial value.


-}
defaultType : Type
defaultType =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Type


{-| Declares how to decode a `Type` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeType : Protobuf.Decode.Decoder Type
decodeType =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Type


{-| Declares how to encode a `Type` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeType : Type -> Protobuf.Encode.Encoder
encodeType =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Type


{-| `Type` message


-}
type alias Type =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Type


{-| Default for SourceContext. Should only be used for 'required' decoders as an initial value.


-}
defaultSourceContext : SourceContext
defaultSourceContext =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__SourceContext


{-| Declares how to decode a `SourceContext` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeSourceContext : Protobuf.Decode.Decoder SourceContext
decodeSourceContext =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__SourceContext


{-| Declares how to encode a `SourceContext` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeSourceContext : SourceContext -> Protobuf.Encode.Encoder
encodeSourceContext =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__SourceContext


{-| `SourceContext` message


-}
type alias SourceContext =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SourceContext


{-| Default for Any. Should only be used for 'required' decoders as an initial value.


-}
defaultAny : Any
defaultAny =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__Any


{-| Declares how to decode a `Any` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeAny : Protobuf.Decode.Decoder Any
decodeAny =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Any


{-| Declares how to encode a `Any` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeAny : Any -> Protobuf.Encode.Encoder
encodeAny =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Any


{-| `Any` message


-}
type alias Any =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Any


{-| Default for NullValue. Should only be used for 'required' decoders as an initial value.


-}
defaultNullValue : NullValue
defaultNullValue =
    NULLVALUE


{-| Convert a `NullValue` into its internal representation `Proto__Google__Protobuf__NullValue`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
toInternalNullValue : NullValue -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValue
toInternalNullValue data_ =
    case data_ of
        NULLVALUE ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NULLVALUE

        NullValueUnrecognized_ n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValueUnrecognized_ n_


{-| Convert the internal type `Proto__Google__Protobuf__NullValue` into a `NullValue`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
fromInternalNullValue : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValue -> NullValue
fromInternalNullValue data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NULLVALUE ->
            NULLVALUE

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValueUnrecognized_ n_ ->
            NullValueUnrecognized_ n_


{-| Declares how to encode a `NullValue` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeNullValue : NullValue -> Protobuf.Encode.Encoder
encodeNullValue =
    toInternalNullValue >> Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__NullValue


{-| Declares how to decode a `NullValue` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeNullValue : Protobuf.Decode.Decoder NullValue
decodeNullValue =
    Protobuf.Decode.map fromInternalNullValue Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__NullValue


{-| `NullValue` enumeration


-}
type NullValue
    = NULLVALUE
    | NullValueUnrecognized_ Int


{-| Default for Syntax. Should only be used for 'required' decoders as an initial value.


-}
defaultSyntax : Syntax
defaultSyntax =
    SYNTAXPROTO2


{-| Convert a `Syntax` into its internal representation `Proto__Google__Protobuf__Syntax`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
toInternalSyntax : Syntax -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Syntax
toInternalSyntax data_ =
    case data_ of
        SYNTAXPROTO2 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SYNTAXPROTO2

        SYNTAXPROTO3 ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SYNTAXPROTO3

        SyntaxUnrecognized_ n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SyntaxUnrecognized_ n_


{-| Convert the internal type `Proto__Google__Protobuf__Syntax` into a `Syntax`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
fromInternalSyntax : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Syntax -> Syntax
fromInternalSyntax data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SYNTAXPROTO2 ->
            SYNTAXPROTO2

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SYNTAXPROTO3 ->
            SYNTAXPROTO3

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SyntaxUnrecognized_ n_ ->
            SyntaxUnrecognized_ n_


{-| Declares how to encode a `Syntax` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeSyntax : Syntax -> Protobuf.Encode.Encoder
encodeSyntax =
    toInternalSyntax >> Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Syntax


{-| Declares how to decode a `Syntax` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeSyntax : Protobuf.Decode.Decoder Syntax
decodeSyntax =
    Protobuf.Decode.map fromInternalSyntax Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Syntax


{-| `Syntax` enumeration


-}
type Syntax
    = SYNTAXPROTO2
    | SYNTAXPROTO3
    | SyntaxUnrecognized_ Int
