{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Google.Protobuf.Value.Kind exposing (Kind(..), boolValue, fromInternalKind, listValue, nullValue, numberValue, stringValue, structValue, toInternalKind)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.3
  - `protoc` 4.22.2
  - the following specification files: `google/protobuf/struct.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Kind, boolValue, fromInternalKind, listValue, nullValue, numberValue, stringValue, structValue, toInternalKind

-}

import Proto.Google.Protobuf.Internals_


{-| Construct a ListValue and immediately turn it into an Internals\_ data type.
This is just (ListValue >> toInternalKind
-}
listValue :
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ListValue
    -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
listValue =
    ListValue >> toInternalKind


{-| Construct a StructValue and immediately turn it into an Internals\_ data type.
This is just (StructValue >> toInternalKind
-}
structValue :
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Struct
    -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
structValue =
    StructValue >> toInternalKind


{-| Construct a BoolValue and immediately turn it into an Internals\_ data type.
This is just (BoolValue >> toInternalKind
-}
boolValue : Bool -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
boolValue =
    BoolValue >> toInternalKind


{-| Construct a StringValue and immediately turn it into an Internals\_ data type.
This is just (StringValue >> toInternalKind
-}
stringValue : String -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
stringValue =
    StringValue >> toInternalKind


{-| Construct a NumberValue and immediately turn it into an Internals\_ data type.
This is just (NumberValue >> toInternalKind
-}
numberValue : Float -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
numberValue =
    NumberValue >> toInternalKind


{-| Construct a NullValue and immediately turn it into an Internals\_ data type.
This is just (NullValue >> toInternalKind
-}
nullValue :
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValue
    -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
nullValue =
    NullValue >> toInternalKind


{-| Convert a `Kind` into its internal representation `Proto__Google__Protobuf__Value__Kind__Kind`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
toInternalKind : Kind -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
toInternalKind data_ =
    case data_ of
        NullValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NullValue n_

        NumberValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NumberValue n_

        StringValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StringValue n_

        BoolValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__BoolValue n_

        StructValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StructValue n_

        ListValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__ListValue n_


{-| Convert the internal type `Proto__Google__Protobuf__Value__Kind__Kind` into a `Kind`.

Using two different types is necessary to avoid recursive module references while having readable constructor names.

-}
fromInternalKind : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind -> Kind
fromInternalKind data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NullValue n_ ->
            NullValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NumberValue n_ ->
            NumberValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StringValue n_ ->
            StringValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__BoolValue n_ ->
            BoolValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StructValue n_ ->
            StructValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__ListValue n_ ->
            ListValue n_


{-| The kind of value.


## Options


### NullValue

Represents a null value.


### NumberValue

Represents a double value.


### StringValue

Represents a string value.


### BoolValue

Represents a boolean value.


### StructValue

Represents a structured value.


### ListValue

Represents a repeated `Value`.

-}
type Kind
    = NullValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValue
    | NumberValue Float
    | StringValue String
    | BoolValue Bool
    | StructValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Struct
    | ListValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ListValue
