{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Google.Protobuf.Value.Kind exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.0.1
- `protoc` 3.19.4
- the following specification files: `google/protobuf/struct.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


-}

import Proto.Google.Protobuf.Internals_


{-| Convert a `Kind` into its internal representation `Proto__Google__Protobuf__Value__Kind__Kind`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
toInternalKind : Kind -> Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind
toInternalKind data_ =
    case data_ of
        NullValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NullValue n_

        NumberValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NumberValue n_

        StringValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StringValue n_

        BoolValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__BoolValue n_

        StructValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StructValue n_

        ListValue n_ ->
            Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__ListValue n_


{-| Convert the internal type `Proto__Google__Protobuf__Value__Kind__Kind` into a `Kind`.


Using two different types is necessary to avoid recursive module references while having readable constructor names.


-}
fromInternalKind : Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__Kind -> Kind
fromInternalKind data_ =
    case data_ of
        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NullValue n_ ->
            NullValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__NumberValue n_ ->
            NumberValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StringValue n_ ->
            StringValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__BoolValue n_ ->
            BoolValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__StructValue n_ ->
            StructValue n_

        Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Value__Kind__ListValue n_ ->
            ListValue n_


{-| `Kind` options


-}
type Kind
    = NullValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__NullValue
    | NumberValue Float
    | StringValue String
    | BoolValue Bool
    | StructValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Struct
    | ListValue Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ListValue
